* Spacemacs Rocks Season 2 (Day 6)
** Bonus Time: Org-mdoe
Use org-capture to take notes
记笔记工具
#+BEGIN_SRC emacs-lisp

  (setq org-capture-templates
        '(("t" "Todo" entry (file+headline "~/.emacs.d/gtd.org" "工作安排")
           "* TODO [#B] %?\n  %i\n"
           :empty-lines 1)))
#+END_SRC
M-x org-capture
(global-set-key (kbd "C-c r") 'org-capture)
(setq org-agenda-files '("~/.emacs.d/"))
C-c a a ;;现在还没有列表（因为没定时间）
gtd.org里某一项：C-c C-s 定时间

安装org-pomodoro: packages; (require 'org-pomodoro)
M-x cust group /org-pomodoro
  long break length: 20 -> 40 ->save future

C-c a a 到某一项上 M-x org-pomodoro[return] 状态栏会显示任务信息。

注：C-x RET f utf-8 RET 存成utf-8
全局设置：(set-language-environment "UTF-8") 
Further reading:
http://orgmode.org/manual/Capture.html
*** Install Org pomodoro to track my time

** clean up configs
1. move keybindings into one place (init.el最后一行，其它el文件中的键绑定均集中在init-keybindings)
2. make c-n and c-p to select company condicate
search: emacs company c-n keybindings ;;将补全下拉列表时M-p/M-n改为C-p/C-n使统一风格
(with-eval-after-load 'company
  (define-key company-active-map (kbd "M-n") nil)
  (define-key company-active-map (kbd "M-p") nil)
  (define-key company-active-map (kbd "C-n") #'company-select-next)
  (define-key company-active-map (kbd "C-p") #'company-select-previous))
** Batch rename files
1. press `C-x C-q` in dired mode
C-x C-j 进入目录buffer. shift+6 进入上级目录。
+ 新建.emacs.d/test-dir
C-x C-f 创建文件hello.txt 输入hello. C 拷贝2个文件hello2.txt hello3.txt1. flycheck-checkers
2. eslint


** Snippets and auto snippet

** exercises
1. give `helm-swoop` package a try: https://github.com/ShingoFukuyama/helm-swoop
2. Give `org-mac-link` package a try: http://melpa.org/#/org-mac-link
